environment:
  SAB_NEWSSERVER_HOST:
    secure: 6SvOPWr5ypJeoumXJAZh90DLpk4C/5UAvzwyX7OOUr4=
  SAB_NEWSSERVER_USER:
    secure: Ty3ZG8T5vnacqIFPj5j5hg==
  SAB_NEWSSERVER_PASSWORD:
    secure: bO3XHtWTleVF9AqRV/V/nA==

  # We only use 64bit to test anyway
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade wheel
  - python -m pip install --upgrade -r requirements.txt
  - python -m pip install --upgrade -r tests/requirements.txt

build_script:
  - python -m pytest